### ISSUE TITLE
Wrong persistance directory liste in Readme

### ISSUE THREAD

**Issue by david-woelfle** [bitnami/bitnami-docker-alertmanager#6]
### Name and Version

bitnami/alertmanager:0.24.0

### What steps will reproduce the bug?

The [documentation about persistance](https://github.com/bitnami/bitnami-docker-alertmanager#persisting-your-application) lists the wrong directory. It says one should bind: 
```-v /path/to/alertmanager-persistence:/opt/bitnami/data```

Correct would be (see [here](https://github.com/bitnami/bitnami-docker-alertmanager/blob/master/0/debian-11/Dockerfile#L31)):
```-v /path/to/alertmanager-persistence:/opt/bitnami/alertmanager/data```

### What is the expected behavior?

The container starts up.

### What do you see instead?

The container doesn't start up and logs permission denied error.

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! Would you like to submit a PR fixing the documentation issue?

**Comment by david-woelfle** [comment]
Hi @javsalgar!

Sure thing see [here](https://github.com/bitnami/bitnami-docker-alertmanager/pull/7).

However, there is some check failing that the commit is not signed, but I don't get what's the problem, as the commit is signed with a GPG key, as you can see above. Any ideas?

**Comment by javsalgar** [comment]
Did you also add the signoff to the commit?

```
git commit --signoff
```
